Email setup config #152238709
andela/healthchecks-apollo pull request #10
Opened 2017-10-27 09:48 UTC by machariamarigi

### What does this PR do

- Allow healthchecks to send emails via gmail.

### Description of the task to be completed

- Configure the application to use a gmail account to send emails to users.

### Pivotal Tracker story

- See [ Chore #152238709](https://www.pivotaltracker.com/story/show/152238709)

2017-10-29 20:42 UTC, ivantoz requested changes
- Can you address the comments I have made on your code
- Also your PR heading and template does not follow our guidelines
- Your commit messages does not adhere to our standards

2017-10-29 20:42 UTC, ivantoz commented on hc/settings.py
> +EMAIL_HOST = 'smtp.gmail.com'
Lets also have this secured

2017-10-29 20:42 UTC, ivantoz commented on hc/settings.py
> +EMAIL_PORT = 587
Same with this

2017-10-29 20:42 UTC, ivantoz commented on hc/settings.py
> -EMAIL_BACKEND = "djmail.backends.default.EmailBackend"
What is the reason for removing this line of code?

2017-10-30 09:43 UTC, machariamarigi commented on hc/settings.py
> -EMAIL_BACKEND = "djmail.backends.default.EmailBackend"
I moved it up to line 26

2017-10-31 05:57 UTC, closed without merging